# Generated by Django 6.0.3 on 2026-07-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_note_slug_alter_book_semester_alter_note_semester_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
